In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('pic1.jpg',0)

hist,bins = np.histogram(img.flatten(),256,[0,256])

cdf = hist.cumsum()
cdf_normalized = cdf * hist.max()/ cdf.max()

In [2]:
cdf

array([    67,    107,    152,    211,    338,    518,    734,   1057,
         1500,   2053,   2706,   3549,   4481,   5585,   6800,   8155,
         9751,  11457,  13264,  15131,  17137,  19196,  21287,  23622,
        26128,  28645,  31372,  34232,  37359,  40378,  43359,  46481,
        49548,  52773,  55957,  59161,  62416,  65782,  69096,  72516,
        76070,  79549,  83188,  86852,  90673,  94463,  98544, 102589,
       106914, 111165, 115609, 120171, 124817, 129495, 134457, 139396,
       144344, 149397, 154442, 159505, 164593, 169514, 174321, 179236,
       184116, 189144, 193999, 198877, 203835, 208613, 213407, 218178,
       223066, 227948, 232931, 237763, 242690, 247576, 252544, 257540,
       262638, 267506, 272474, 277506, 282331, 287075, 291960, 296779,
       301523, 306441, 311380, 316155, 320988, 325675, 330334, 334933,
       339684, 344390, 348981, 353685, 358115, 362566, 366952, 371271,
       375583, 379710, 383898, 388105, 392326, 396534, 400758, 404982,
      

In [3]:
bins

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [4]:
int(bins)

TypeError: only size-1 arrays can be converted to Python scalars

In [5]:
bin_new = int(bins)

TypeError: only size-1 arrays can be converted to Python scalars

In [7]:
cdf_normalized

array([5.44957920e-01, 8.70305931e-01, 1.23632244e+00, 1.71621076e+00,
       2.74919070e+00, 4.21325675e+00, 5.97013601e+00, 8.59732121e+00,
       1.22005504e+01, 1.66984867e+01, 2.20097930e+01, 2.88665023e+01,
       3.64471110e+01, 4.54267161e+01, 5.53091620e+01, 6.63303259e+01,
       7.93117115e+01, 9.31878042e+01, 1.07885401e+02, 1.23071019e+02,
       1.39387222e+02, 1.56134511e+02, 1.73142078e+02, 1.92134268e+02,
       2.12517321e+02, 2.32989845e+02, 2.55170446e+02, 2.78432828e+02,
       3.03866909e+02, 3.28422550e+02, 3.52669111e+02, 3.78062523e+02,
       4.03008582e+02, 4.29239765e+02, 4.55137467e+02, 4.81197843e+02,
       5.07673037e+02, 5.35051073e+02, 5.62006155e+02, 5.89823410e+02,
       6.18730581e+02, 6.47027724e+02, 6.76626260e+02, 7.06428138e+02,
       7.37507007e+02, 7.68333731e+02, 8.01527361e+02, 8.34428179e+02,
       8.69606433e+02, 9.04182793e+02, 9.40328957e+02, 9.77434898e+02,
       1.01522407e+03, 1.05327352e+03, 1.09363294e+03, 1.13380529e+03,
      

In [8]:
cdf_m = np.ma.masked_equal(cdf,0)

In [9]:
cdf_m

masked_array(data=[    67,    107,    152,    211,    338,    518,    734,
                     1057,   1500,   2053,   2706,   3549,   4481,   5585,
                     6800,   8155,   9751,  11457,  13264,  15131,  17137,
                    19196,  21287,  23622,  26128,  28645,  31372,  34232,
                    37359,  40378,  43359,  46481,  49548,  52773,  55957,
                    59161,  62416,  65782,  69096,  72516,  76070,  79549,
                    83188,  86852,  90673,  94463,  98544, 102589, 106914,
                   111165, 115609, 120171, 124817, 129495, 134457, 139396,
                   144344, 149397, 154442, 159505, 164593, 169514, 174321,
                   179236, 184116, 189144, 193999, 198877, 203835, 208613,
                   213407, 218178, 223066, 227948, 232931, 237763, 242690,
                   247576, 252544, 257540, 262638, 267506, 272474, 277506,
                   282331, 287075, 291960, 296779, 301523, 306441, 311380,
                   316155

In [10]:
cdf_m = (cdf_m - cdf_m.min())*255/(cdf_m.max()-cdf_m.min())
cdf = np.ma.filled(cdf_m,0).astype('uint8')

In [11]:
cdf_m

masked_array(data=[0.0, 0.016275522252787583, 0.03458548478717361,
                   0.05859188011003529, 0.11026666326263587,
                   0.18350651340017998, 0.27139433356523296,
                   0.4028191757564927, 0.5830705847061152,
                   0.8080796798509035, 1.0737775806276608,
                   1.416784212105159, 1.7960038805951097,
                   2.245208294772047, 2.73957728320047, 3.290910599513649,
                   3.940303937399874, 4.634454961481264,
                   5.369701679250943, 6.1293616803998034,
                   6.945579121377101, 7.783361629339342,
                   8.634164555103812, 9.584248166610287,
                   10.60390963574743, 11.628046873504088,
                   12.737630603087881, 13.901330444162193,
                   15.173669396273862, 16.402064438303004,
                   17.614997734192, 18.88530224602207, 20.13322791475456,
                   21.445441896385557, 22.740973467707448,
                   24.

In [12]:
cdf

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   1,   1,
         2,   2,   3,   3,   4,   5,   6,   6,   7,   8,   9,  10,  11,
        12,  13,  15,  16,  17,  18,  20,  21,  22,  24,  25,  26,  28,
        29,  30,  32,  33,  35,  36,  38,  40,  41,  43,  45,  47,  48,
        50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100,
       102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
       128, 130, 132, 134, 136, 138, 140, 141, 143, 145, 147, 149, 151,
       152, 154, 156, 157, 159, 161, 163, 164, 166, 168, 169, 171, 173,
       174, 176, 178, 179, 181, 183, 184, 186, 187, 189, 190, 192, 194,
       195, 197, 198, 200, 201, 203, 204, 206, 207, 208, 209, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 220, 221, 222, 223, 224,
       225, 226, 227, 227, 228, 229, 230, 230, 231, 232, 232, 233, 234,
       234, 235, 235, 236, 236, 237, 237, 238, 238, 239, 239, 24

In [13]:
img2 = cdf[img]

In [14]:
cv.imshow('output',img2)

NameError: name 'cv' is not defined

In [15]:
cv2.imshow('output',img2)

In [16]:
len(cdf)

256